from typing import Protocol
from uuid import UUID

from app.domain.event import WorkflowEvent, WorkflowEventCreate
from app.domain.workflow import Workflow, WorkflowState

# Invariant:
# A workflow snapshot is only created for a user-visible waiting state.
# Creation/branching events explain how we arrived at that snapshot,
# but do not create snapshots by themselves.


class WorkflowRepository(Protocol):
    def insert_workflow(self, workflow: Workflow, events: list[WorkflowEventCreate] | None = None) -> Workflow: ...
    def get_workflow(self, workflow_id: UUID) -> Workflow | None: ...
    def get_workflows(self) -> list[Workflow]: ...
    def update_workflow(self, workflow: Workflow, events: list[WorkflowEventCreate] | None = None) -> Workflow: ...
    def get_events(self, workflow_id: UUID) -> list[WorkflowEvent]: ...
    def get_current_snapshot_id(self, workflow_id: UUID) -> UUID: ...
    def get_snapshot(self, workflow_id: UUID, snapshot_id: UUID) -> WorkflowState: ...
