from typing import Protocol
from uuid import UUID

from app.domain.workflow import Workflow, WorkflowCreate, WorkflowHistory


class WorkflowRepository(Protocol):
    def create(self, workflow_create: WorkflowCreate) -> Workflow: ...
    def get(self, workflow_id: UUID) -> Workflow | None: ...
    def list(self) -> list[Workflow]: ...
    def save(self, workflow: Workflow) -> Workflow: ...
    def branch(self, snapshot_id: UUID) -> Workflow: ...
    def history(self, workflow_id: UUID) -> WorkflowHistory: ...
