from typing import Protocol
from uuid import UUID

from app.domain.workflow import WorkflowState, WorkflowStateCreate


class WorkflowRepository(Protocol):
    def create(self, workflow_create: WorkflowStateCreate) -> WorkflowState: ...
    def get(self, workflow_id: UUID) -> WorkflowState | None: ...
    def list(self) -> list[WorkflowState]: ...
    def save(self, workflow: WorkflowState) -> WorkflowState: ...
