import logging

from app.application.solution_service import SolutionService
from app.domain.streaming import StreamSink
from app.domain.workflow import Solution, WorkflowContext

logger = logging.getLogger(__name__)


class ParrotSolutionService(SolutionService):
    def generate_solution(
        self,
        ctx: WorkflowContext,
        stream: StreamSink | None = None,
    ) -> Solution:
        if stream:
            logger.warning("Streaming not supported in ParrotSolutionService; ignoring stream parameter.")

        # Format steps in a readable, intentional way
        if ctx.steps:
            steps_md = "\n".join(
                f"- **Step {i + 1}**: {step.prompt} → _{step.answer or 'no answer'}_"
                for i, step in enumerate(ctx.steps)
            )
        else:
            steps_md = "_No steps recorded._"

        # Format chat history as a transcript
        if ctx.chat_history.messages:
            chat_md = "\n".join(
                f"- **{msg.role.value.capitalize()}**: {msg.content}" for msg in ctx.chat_history.messages
            )
        else:
            chat_md = "_No chat messages._"

        content = f"""
## Parrot Test Workflow Result

This solution was generated by the **Parrot test domain**.

This domain is intentionally deterministic and **does not attempt to solve a problem**.
Each clarification step asks for more input, and chat messages are echoed back verbatim.

---

### Collected Steps
{steps_md}

---

### Chat Transcript
{chat_md}
        """.strip()

        confidence = ctx.last_decision.workflow_confidence if ctx.last_decision else 0.5

        return Solution(
            content=content,
            confidence=confidence,
            rationale="Deterministic test output generated by ParrotSolutionService.",
        )
